Fixed Bug:
java.lang.IllegalArgumentException: the bind value at index 2 is null
at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:234)
at android.database.sqlite.SQLiteQuery.bindString(SQLiteQuery.java:182)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:59)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1412)
at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1296)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1251)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1331)
at net.sourceforge.servestream.dbutils.StreamDatabase.findStream(StreamDatabase.java:248)
at net.sourceforge.servestream.StreamListActivity.saveStream(StreamListActivity.java:362)
at net.sourceforge.servestream.StreamListActivity.access$3(StreamListActivity.java:361)
at net.sourceforge.servestream.StreamListActivity$3.onClick(StreamListActivity.java:161)

git-svn-id: http://svn.code.sf.net/p/servestream/code/trunk@212 b8d320ad-ce4d-463a-8333-51e6c77ad906